version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "github.com/kkdai/youtube/v2"
        dependency-type: "all"
    commit-message:
      prefix: "chore(deps): update dependency github.com/kkdai/youtube/v2 to latest version"
